import React, { useState, useMemo, useEffect } from 'react';
import { db } from '@/config/supabase';
import * as XLSX from 'xlsx';
import { usePayables } from '@/hooks/usePayables';
import { useBills } from '@/hooks/useBills';
import { useAuth } from '@/hooks/useAuth';
import { Button, Modal } from '@/components/ui';
import { DataTable, Column } from '@/components/ui/DataTable';
import type { Payable, BankAccount, Bill } from '@/types/bill.types';

import { PayableFormModal } from './modals/PayableFormModal';
import { VendorLedgerModal, VendorLedgerData } from './modals/VendorLedgerModal';
import { BulkPayModal, BulkPayPreviewRow } from './modals/BulkPayModal';

const openPrint = (html: string) => {
  const w = window.open('', '_blank', 'width=1000,height=780');
  if (!w) return;
  w.document.write(html);
  w.document.close();
  setTimeout(() => w.print(), 700);
};

const printPDF = (title: string, html: string) => {
  const fullHtml = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; font-size: 11px; color: #1e293b; padding: 20px; }
        h1 { font-size: 18px; margin-bottom: 4px; color: #0f172a; }
        .sub { font-size: 10px; color: #64748b; margin-bottom: 20px; text-transform: uppercase; letter-spacing: 1px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background: #f1f5f9; color: #475569; padding: 8px 10px; text-align: left; font-size: 9px; text-transform: uppercase; letter-spacing: 1px; border: 1px solid #e2e8f0; }
        td { padding: 8px 10px; border: 1px solid #e2e8f0; vertical-align: top; }
        .hdr { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #0f172a; padding-bottom: 10px; margin-bottom: 20px; }
        .co { font-size: 14px; font-weight: 800; color: #0f172a; }
        .footer { margin-top: 30px; font-size: 9px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 10px; }
        .mono { font-family: monospace; }
        @media print { body { padding: 0; } .no-print { display: none; } }
      </style>
    </head>
    <body>
      <div class="hdr">
        <div>
          <div class="co">P. Sunny Engineering Contractors (OPC) Pvt. Ltd.</div>
          <div class="sub">${title} &bull; ${new Date().toLocaleDateString('en-IN')}</div>
        </div>
      </div>
      ${html}
      <div class="footer">Generated by SunnyOps &bull; P. Sunny Engineering Contractors (OPC) Pvt. Ltd.</div>
    </body>
    </html>
  `;
  openPrint(fullHtml);
};

export const PayablesTab: React.FC = () => {
  const auth = useAuth();
  const { payables, loading: pLoading, save: savePayable, saveMany: saveManyPayables, remove: removePayable } = usePayables();
  const { bills } = useBills();

  const [vendorSearch, setVendorSearch] = useState('');
  const [modal, setModal] = useState<"form" | null>(null);
  const [vendorLedger, setVendorLedger] = useState<VendorLedgerData | null>(null);

  // Bank State (Fetched from app_settings)
  const [banks, setBanks] = useState<BankAccount[]>([]);
  const [bankBalanceRaw, setBankBalanceRaw] = useState<any>(null);
  const [bbUpdated, setBbUpdated] = useState<string | null>(null);

  useEffect(() => {
    const fetchBanks = async () => {
      const { data: bData } = await db.from('app_settings').select('value, updated_at').eq('key', 'banks').single();
      if (bData?.value) {
        setBanks(bData.value as BankAccount[]);
        setBbUpdated(bData.updated_at);
      }
      const { data: bbData } = await db.from('app_settings').select('value').eq('key', 'bank_balance').single();
      if (bbData?.value) setBankBalanceRaw(bbData.value);
    };
    fetchBanks();
  }, []);

  const bankBalance = bankBalanceRaw?.amount || bankBalanceRaw || "0";

  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState<Partial<Payable>>({});

  // Card details
  const [cardDetail, setCardDetail] = useState<string | null>(null);
  const [cdFrom, setCdFrom] = useState("");
  const [cdTo, setCdTo] = useState("");
  const [cdSite, setCdSite] = useState("");

  const [showBulkPay, setShowBulkPay] = useState(false);
  const [bpForm, setBpForm] = useState({ vendor: "", amount: "", paid_date: new Date().toISOString().slice(0, 10), payment_mode: "NEFT", remarks: "" });
  const [bpResult, setBpResult] = useState<{ ok: boolean, msg: string } | null>(null);

  const SITES = ["MRPL", "MEIL", "UPCL", "BTPS-Bellary", "Moxi", "Head Office", "GODOWN", "ADANI", "KPCL", "Anpara-Lanco"];

  const isAdmin = auth.userRole === 'admin' || auth.userRole === 'managing-director';
  const canEdit = isAdmin;
  const today = new Date();

  const filteredPayables = useMemo(() => {
    let res = payables;
    if (vendorSearch.trim()) {
      const q = vendorSearch.toLowerCase();
      res = res.filter(p => p.vendor?.toLowerCase().includes(q) || p.invoice_no?.toLowerCase().includes(q) || p.site?.toLowerCase().includes(q));
    }
    return res;
  }, [payables, vendorSearch]);

  const totalPending = payables.filter(p => p.status !== "Paid").reduce((s, p) => s + parseFloat(p.amount as string || "0"), 0);
  const totalPaid = payables.filter(p => p.status === "Paid").reduce((s, p) => s + parseFloat(p.amount as string || "0"), 0);
  const partialPaid = payables.filter(p => p.status === "Partial").reduce((s, p) => {
    const m = (p.remarks as string)?.match(/Paid [^0-9]*([0-9][0-9,]*)/);
    return s + (m ? parseInt(m[1].replace(/,/g, ""), 10) : 0);
  }, 0);
  const totalPaidDisplay = totalPaid + partialPaid;
  
  const overdue = payables.filter(p => p.status !== "Paid" && p.due_date && new Date(p.due_date) < today).length;

  const siteOutstanding = useMemo(() => {
    const siteList = ["MRPL", "MEIL", "UPCL", "BTPS-Bellary", "Moxi", "GODOWN", "Head Office"];
    return siteList.map(s => {
      const sp = payables.filter(p => p.site === s && p.status !== "Paid");
      return {
        site: s,
        amt: sp.reduce((sum, p) => sum + parseFloat(p.amount as string || "0"), 0),
        count: sp.length
      };
    }).sort((a, b) => b.amt - a.amt);
  }, [payables]);

  const getBal = (b: Bill) => {
    const stored = parseFloat(b.balance_to_receive as any || "0");
    if (stored > 0) return stored;
    if (b.bill_status === "RECEIVED" || b.bill_status === "CANCELLED") return 0;

    const base = parseFloat(b.amount_with_gst as any || b.amount as any || "0");
    const deductions = [
      b.tds, b.tds_on_gst, b.security_deposit, b.hra_deduction, 
      b.gst_hold, b.other_deductions, b.credit_note, b.credit_note2
    ].reduce((s: number, v: any) => s + parseFloat(v?.toString() || "0"), 0);
    
    const received = [
      b.hra_received, b.sd_received, b.gst_received, 
      b.others_received, b.amount_credited
    ].reduce((s: number, v: any) => s + parseFloat(v?.toString() || "0"), 0);
    
    return Math.max(0, base - deductions - received);
  };
  const totalReceivable = bills.filter(b => b.bill_status !== "CANCELLED").reduce((s, b) => s + getBal(b), 0);

  const bb = banks.length > 0 
    ? banks.reduce((s, b) => s + (b.isOD ? Math.min(0, parseFloat((b.balance as any) || "0")) : parseFloat((b.balance as any) || "0")), 0) 
    : parseFloat(bankBalance || "0");
  const odUsed = banks.filter(b => b.isOD).reduce((s, b) => s + Math.max(0, parseFloat((b.balance as any) || "0")), 0);
  const netPos = bb + totalReceivable - totalPending;

  const fmt = (n: number) => n >= 10000000 ? (n / 10000000).toFixed(2) + "Cr" : n >= 100000 ? (n / 100000).toFixed(2) + "L" : n >= 1000 ? (n / 1000).toFixed(1) + "K" : n.toLocaleString("en-IN", { maximumFractionDigits: 0 });

  const openForm = (p: Payable | null) => {
    if (p) {
      setForm({ ...p });
    } else {
      setForm({ amount: "", gst_percent: "18", amount_with_gst: "", due_date: "", paid_date: "", status: "Pending", category: "Material", payment_mode: "", site: SITES[0] });
    }
    setModal("form");
  };

  const handleSave = async () => {
    if (!form.vendor || !form.amount || !form.due_date) {
      alert("Vendor, Amount and Due Date are required");
      return;
    }
    if (!form.id && form.invoice_no && payables.find(p => p.vendor === form.vendor && p.invoice_no === form.invoice_no)) {
      if (!window.confirm(`Invoice No ${form.invoice_no} already exists for ${form.vendor}. Add anyway?`)) return;
    }
    setSaving(true);
    const payload = {
      ...form,
      amount: form.amount?.toString() || "0",
      amount_with_gst: form.amount_with_gst ? form.amount_with_gst.toString() : "",
      created_by: auth.userName,
    } as Omit<Payable, 'id' | 'created_at'>;
    
    const err = await savePayable(payload, form.id);
    setSaving(false);
    if (err) alert(err);
    else setModal(null);
  };

  const handleSaveBanks = async (newBanks: BankAccount[]) => {
    setSaving(true);
    const { error } = await db.from('app_settings').upsert({ key: 'banks', value: newBanks, updated_at: new Date().toISOString() }, { onConflict: 'key' });
    setSaving(false);
    if (error) alert(error.message);
    else setBanks(newBanks);
  };

  const handleSaveBankBalance = async (newBal: string) => {
    setSaving(true);
    const { error } = await db.from('app_settings').upsert({ key: 'bank_balance', value: { amount: newBal }, updated_at: new Date().toISOString() }, { onConflict: 'key' });
    setSaving(false);
    if (error) alert(error.message);
    else setBankBalanceRaw({ amount: newBal });
  };

  const onDelete = async (id: string) => {
    setSaving(true);
    const err = await removePayable(id);
    setSaving(false);
    if (err) alert(err);
  };

  const openVendorLedger = (vendorName: string) => {
    const invs = payables.filter(p => p.vendor === vendorName).sort((a, b) => new Date(a.due_date || 0).getTime() - new Date(b.due_date || 0).getTime());
    let tAmt = 0, tPaid = 0;
    invs.forEach(p => {
      const v = parseFloat(p.amount as string || "0");
      tAmt += v;
      if (p.status === "Paid") tPaid += v;
      if (p.status === "Partial") {
        const m = (p.remarks as string)?.match(/Paid [^0-9]*([0-9][0-9,]*)/);
        tPaid += m ? parseInt(m[1].replace(/,/g, ""), 10) : 0;
      }
    });
    
    // Exact mapping for gst calculations 
    let tGst = 0;
    let tWithGst = 0;
    invs.forEach(p => {
       const b = parseFloat(p.amount as string || "0");
       const g = parseFloat(p.gst_percent || "18");
       const inc = p.amount_with_gst ? parseFloat(p.amount_with_gst as string) : b * (1 + g/100);
       tWithGst += inc;
       tGst += (inc - b);
    });

    setVendorLedger({
      vendor: vendorName,
      gstin: invs.find(p => p.vendor_gstin)?.vendor_gstin,
      totalAmt: tAmt,
      totalGst: tGst,
      totalWithGst: tWithGst,
      totalPaidAmt: tPaid,
      totalPendAmt: tWithGst - tPaid,
      invoices: invs
    });
  };

  const handlePayExportTemplate = () => {
    const headers = ["VENDOR", "VENDOR_GSTIN", "SITE", "CATEGORY", "INVOICE_NO", "PO_NO", "DESCRIPTION", "BASE_AMOUNT", "GST_PERCENT", "TOTAL_WITH_GST", "DUE_DATE", "STATUS", "PAID_DATE", "PAYMENT_MODE", "REMARKS"];
    const sample = [["Cement Suppliers Ltd", "29XXXXX1234X1Z1", "MRPL", "Material", "INV/2024/001", "PO/001", "OPC Cement 500 bags", "50000", "18", "59000", "2025-01-31", "Pending", "", "NEFT", "As per WO"]];
    const ws = XLSX.utils.aoa_to_sheet([headers, ...sample]);
    ws["!cols"] = headers.map(() => ({ wch: 20 }));
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Payables");
    XLSX.writeFile(wb, "Payables_Template.xlsx");
  };

  const handlePayImport = async (file: File) => {
    try {
      const data = await file.arrayBuffer();
      const wb = XLSX.read(data, { type: "array", cellDates: true });
      const ws = wb.Sheets[wb.SheetNames[0]];
      const rows = XLSX.utils.sheet_to_json(ws, { defval: "" }) as any[];
      
      const getCol = (row: any, aliases: string[]) => {
        const keys = Object.keys(row);
        for (const al of aliases) {
          const normAl = al.toUpperCase().replace(/[^A-Z0-9]/g, "");
          for (const kn of keys) {
            if (kn.toUpperCase().replace(/[^A-Z0-9]/g, "") === normAl) {
              return String(row[kn] || "").trim();
            }
          }
        }
        return "";
      };

      const payloads: Omit<Payable, 'id' | 'created_at'>[] = [];
      for (const row of rows) {
        const vendor = getCol(row, ["VENDOR", "VENDOR NAME", "SUPPLIER"]);
        if (!vendor) continue;
        const amount = parseFloat(getCol(row, ["BASE_AMOUNT", "BASIC AMT"]) || "0");
        if (amount <= 0) continue;

        payloads.push({
          vendor,
          vendor_gstin: getCol(row, ["VENDOR_GSTIN", "GSTIN"]) || undefined,
          site: getCol(row, ["SITE", "LOCATION"]) || "MRPL",
          category: getCol(row, ["CATEGORY", "TYPE"]) || "Material",
          invoice_no: getCol(row, ["INVOICE_NO", "BILL NO"]) || undefined,
          po_no: getCol(row, ["PO_NO", "WORK ORDER"]) || undefined,
          description: getCol(row, ["DESCRIPTION", "DETAILS"]) || undefined,
          amount,
          gst_percent: getCol(row, ["GST_PERCENT"]) || "18",
          amount_with_gst: parseFloat(getCol(row, ["TOTAL_WITH_GST", "TOTAL AMT"]) || "0") || undefined,
          due_date: getCol(row, ["DUE_DATE"]),
          status: getCol(row, ["STATUS"]) || "Pending",
          paid_date: getCol(row, ["PAID_DATE"]) || undefined,
          payment_mode: getCol(row, ["PAYMENT_MODE", "MODE"]) || undefined,
          remarks: getCol(row, ["REMARKS", "NOTES"]) || undefined,
          created_by: auth.userName,
        });
      }

      if (payloads.length > 0) {
        const err = await saveManyPayables(payloads);
        if (err) alert(err);
        else alert(`Imported ${payloads.length} records successfully!`);
      }
    } catch (err: any) {
      alert("Import failed: " + err.message);
    }
  };

  const handleMonthlyExpenseImport = async (file: File) => {
    try {
      const data = await file.arrayBuffer();
      const wb = XLSX.read(data, { type: "array", cellDates: true });
      const ws = wb.Sheets[wb.SheetNames[0]];
      const rows = XLSX.utils.sheet_to_json(ws, { defval: null, raw: false, dateNF: "YYYY-MM-DD" }) as any[];
      
      const COL_SITE_MAP: any = { "MRPL": "MRPL", "GAIL": "MEIL", "MOXI": "Moxi", "MEIL": "MEIL", "UPCL": "UPCL", "BTPS": "BTPS-Bellary", "OTHERS": "Head Office" };
      const CAT_MAP: any = { "SALARIES": "Monthly Salary", "SALARY": "Monthly Salary", "CONSUMABLES": "Material", "OXYGEN/DA": "Material", "DIESEL": "Site Expense", "ROOM RENT": "Site Expense", "FOOD EXP IF ANY": "Site Expense", "FOOD": "Site Expense", "VEHICLE RENTALS": "Equipment Hire", "VEHICLE RENTAL": "Equipment Hire", "ELECTRICITY": "Site Expense", "MEDICAL": "Site Expense", "RENTALS": "Site Expense", "BUSINESS PROMOTION": "Site Expense", "SUBCONTRACTOR CHARGES": "Subcontract", "INSULATION CHARGES": "Subcontract", "ADVANCE PAID": "Site Expense", "STATUTORY EXPENSE": "Site Expense", "TRAVEL EXPENSE": "Site Expense", "TRAVEL & MOBIL": "Site Expense", "VEHICLE REPAIR": "Site Expense", "TRANSPORTATION CHARGES": "Transport", "TRANSPOTATION CHARGES": "Transport", "TESTING CHARGES": "Service", "INCENTIVE PAID": "Monthly Salary", "INCENTIVES PAID": "Monthly Salary", "MIS EXPENSE": "Site Expense", "MIS EXP": "Site Expense", "SCAFFOLDING CHARGES": "Subcontract", "VEHICLE MAINTENANCE": "Site Expense", "INSURANCE EXPENSE": "Site Expense", "VEHICLE PURCHASE": "Site Expense", "VEHICLES PURCHASE": "Site Expense" };
      
      let added = 0, dupes = 0;
      let currentMonth: Date | null = null;

      const payloads: Omit<Payable, 'id' | 'created_at'>[] = [];

      for (let i = 0; i < rows.length; i++) {
        const row = rows[i];
        const monthVal = row["MONTH"] || row["Month"] || row[Object.keys(row)[0]];
        const descVal = (row["DESCRIPTION"] || row["Description"] || row[Object.keys(row)[1]] || "").toString().trim();
        
        if (monthVal && monthVal !== "MONTH" && monthVal !== "DESCRIPTION") {
          const parsedDate = new Date(monthVal);
          if (!isNaN(parsedDate.getTime()) && parsedDate.getFullYear() > 2000) {
            currentMonth = parsedDate;
          }
        }

        if (!currentMonth || !descVal || ["DESCRIPTION", "MONTH", "CUMILATIVE"].includes(descVal.toUpperCase())) continue;

        const dueDate = new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1, 0);
        const dueDateStr = dueDate.toISOString().slice(0, 10);
        const monthLabel = currentMonth.toLocaleDateString("en-IN", { month: "short", year: "numeric" });
        const catKey = descVal.toUpperCase().replace(/[^A-Z \/&]/g, "").trim();
        const category = CAT_MAP[catKey] || "Site Expense";

        for (const col in COL_SITE_MAP) {
          const rawVal = row[col] || row[col.charAt(0) + col.slice(1).toLowerCase()];
          if (!rawVal) continue;

          let amt = 0;
          if (typeof rawVal === "number") {
            amt = rawVal;
          } else {
            const strVal = String(rawVal).replace(/=/g, "");
            try {
              amt = strVal.split("+").reduce((s, p) => s + (parseFloat(p) || 0), 0);
            } catch {
              amt = 0;
            }
          }

          if (amt <= 0) continue;
          const appSite = COL_SITE_MAP[col];

          const isDupe = payables.some(p => p.description?.includes(monthLabel) && p.description?.includes(descVal) && p.site === appSite);
          if (isDupe) {
            dupes++;
            continue;
          }

          payloads.push({
            vendor: "Monthly Expense",
            vendor_gstin: "",
            site: appSite,
            category,
            invoice_no: `EXP/${currentMonth.getFullYear()}/${String(currentMonth.getMonth() + 1).padStart(2, "0")}/${col}`,
            po_no: "",
            description: `${monthLabel} — ${descVal}`,
            amount: Math.round(amt),
            gst_percent: "0",
            amount_with_gst: Math.round(amt),
            due_date: dueDateStr,
            status: "Pending",
            paid_date: undefined,
            payment_mode: "",
            remarks: "Imported from Monthly Expense Report",
            created_by: auth.userName,
          });
          added++;
        }
      }

      if (payloads.length > 0) {
        const err = await saveManyPayables(payloads);
        if (err) alert(err);
        else alert(`Monthly Expense Import: ${added} added, ${dupes} skipped.`);
      } else if (dupes > 0) {
        alert(`All records already exist (${dupes} skipped).`);
      }
    } catch (err: any) {
      alert("Import failed: " + err.message);
    }
  };

  const handlePrintRegister = () => {
    let html = `<table><thead><tr><th>#</th><th>Vendor</th><th>Site</th><th>Description</th><th>Amount (₹)</th><th>Due Date</th><th>Status</th></tr></thead><tbody>`;
    filteredPayables.forEach((p, i) => {
      html += `<tr><td>${i+1}</td><td><b>${p.vendor}</b>${p.vendor_gstin ? `<br><small>${p.vendor_gstin}</small>` : ''}</td><td>${p.site}</td><td>${p.description || '-'}</td><td class="mono" style="text-align:right">${parseFloat(p.amount as string || '0').toLocaleString('en-IN')}</td><td>${p.due_date || '-'}</td><td>${p.status}</td></tr>`;
    });
    html += `</tbody></table>`;
    printPDF("Payables Register", html);
  };

  const onBulkPay = async (preview: BulkPayPreviewRow[], submitForm: any) => {
    for (let i = 0; i < preview.length; i++) {
        const row = preview[i];
        if (row.pay > 0) {
            const upd: any = { status: row.status, paid_date: submitForm.paid_date, payment_mode: submitForm.payment_mode };
            if (submitForm.remarks) upd.remarks = submitForm.remarks;
            await savePayable(upd, row.p.id);
        }
    }
    return { ok: true, msg: "Payment applied successfully!" };
  };

  const cardDetailItems = (key: string | null) => {
    if (!key) return [];
    if (key === "od") return []; // Handled separately in Modal UI

    let items = payables;
    if (cdSite) items = items.filter(p => p.site === cdSite);
    if (cdFrom && cdTo) items = items.filter(p => {
       const dt = p.due_date || (p as any).created_at?.slice(0, 10) || "";
       return dt >= cdFrom && dt <= cdTo;
    });

    if (key.startsWith("site:")) {
      const s = key.slice(5);
      return items.filter(p => p.site === s && p.status !== "Paid");
    }
    if (key === "receivable") {
      let bItems = bills;
      if (cdSite) bItems = bItems.filter(b => b.site === cdSite);
      return bItems.filter(b => b.bill_status !== "CANCELLED" && getBal(b) !== 0);
    }
    if (key === "outstanding") return items.filter(p => p.status !== "Paid");
    if (key === "overdue") return items.filter(p => p.status !== "Paid" && p.due_date && new Date(p.due_date) < today);
    if (key === "paid") return items.filter(p => p.status === "Paid" || p.status === "Partial");
    if (key === "net") return items;
    return items;
  };

  const printCardPDF = (key: string) => {
    const items = cardDetailItems(key);
    const isReceivable = key === "receivable";
    const title = key.startsWith("site:") ? `Outstanding: ${key.slice(5)}` : ({ outstanding: "Outstanding Payables", overdue: "Overdue Payables", receivable: "Bills Receivable", net: "All Payables", paid: "Paid This Cycle", od: "OD Utilization" } as any)[key] || key;

    let html = "";
    if (key === "od") {
      html = `<table><thead><tr><th>#</th><th>BANK NAME</th><th>ACCOUNT NO</th><th style="text-align:right">LIMIT</th><th style="text-align:right">USED</th></tr></thead><tbody>`;
      banks.filter(b => b.isOD).forEach((b, i) => {
        html += `<tr><td>${i + 1}</td><td><b>${b.name}</b></td><td>${b.account_no}</td><td style="text-align:right">₹${(b.odLimit || 0).toLocaleString("en-IN")}</td><td style="text-align:right;color:#dc2626;font-weight:bold">₹${parseFloat(b.balance as any || 0).toLocaleString("en-IN")}</td></tr>`;
      });
      html += `</tbody></table>`;
    } else {
      html = `<table><thead><tr><th>#</th><th>${isReceivable ? "INV NO" : "VENDOR"}</th><th>SITE</th><th>DESCRIPTION</th><th style="text-align:right">${isReceivable ? "BILLED" : "BASE AMT"}</th><th style="text-align:right">${isReceivable ? "BALANCE" : "DUE DATE"}</th><th>STATUS</th></tr></thead><tbody>`;
      items.forEach((p: any, n: number) => {
        if (isReceivable) {
          html += `<tr><td>${n + 1}</td><td><b>${p.inv_no}</b></td><td>${p.site}</td><td>${p.bill_details || "-"}</td><td style="text-align:right">₹${parseFloat(p.amount_with_gst || 0).toLocaleString("en-IN")}</td><td style="text-align:right;color:#dc2626;font-weight:bold">₹${getBal(p).toLocaleString("en-IN")}</td><td>${p.bill_status}</td></tr>`;
        } else {
          html += `<tr><td>${n + 1}</td><td><b>${p.vendor}</b>${p.vendor_gstin ? `<br><small>${p.vendor_gstin}</small>` : ""}</td><td>${p.site}</td><td>${p.description || "-"}</td><td style="text-align:right">₹${parseFloat(p.amount || 0).toLocaleString("en-IN")}</td><td>${p.due_date ? new Date(p.due_date).toLocaleDateString("en-IN") : "-"}</td><td>${p.status}</td></tr>`;
        }
      });
      html += `</tbody></table>`;
    }
    
    html += `<p style="font-size:10px;color:#64748b;margin-top:10px">Total: ${items.length || banks.filter(b => b.isOD).length} records</p>`;
    printPDF(title, html);
  };

  const columns: Column<Payable>[] = [
    { header: 'Vendor', render: (p) => (
      <div onClick={() => openVendorLedger(p.vendor)} style={{ fontWeight: 600, color: '#1d4ed8', cursor: 'pointer', textDecoration: 'underline' }} title="Click to view vendor ledger">
        {p.vendor}
      </div>
    )},
    { header: 'Site', render: (p) => (
      <span style={{ background: '#fff7ed', border: '1px solid #fed7aa', color: '#ea580c', borderRadius: 4, padding: '2px 7px', fontSize: 10, fontWeight: 700 }}>{p.site}</span>
    )},
    { header: 'Description', render: (p) => (
      <div style={{ color: '#64748b', maxWidth: 200, fontSize: 11 }}>{p.description || "—"}</div>
    )},
    { header: 'Amount', align: 'right', render: (p) => (
      <div style={{ fontWeight: 700, color: '#dc2626', fontFamily: 'IBM Plex Mono, monospace' }}>
        ₹{parseFloat(p.amount as string || "0").toLocaleString("en-IN", { maximumFractionDigits: 0 })}
      </div>
    )},
    { header: 'GST Amt', align: 'right', render: (p) => (
      <div style={{ color: '#7c3aed', fontFamily: 'IBM Plex Mono, monospace', fontSize: 11 }}>
        {p.amount_with_gst 
          ? `₹${(parseFloat(p.amount_with_gst as string || "0") - parseFloat(p.amount as string || "0")).toLocaleString("en-IN", { maximumFractionDigits: 0 })}` 
          : `₹${(parseFloat(p.amount as string || "0") * (parseFloat(p.gst_percent || "18") / 100)).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`}
      </div>
    )},
    { header: 'Due Date', render: (p) => {
      const isOverdue = p.status !== "Paid" && p.due_date && new Date(p.due_date) < today;
      return (
        <div style={{ color: isOverdue ? "#dc2626" : "#64748b", fontWeight: isOverdue ? 700 : 400 }}>
          {p.due_date ? new Date(p.due_date).toLocaleDateString("en-IN") : "—"}
          {isOverdue && <span style={{ fontSize: 9, marginLeft: 4, color: "#dc2626" }}>OVERDUE</span>}
        </div>
      );
    }},
    { header: 'Status', render: (p) => {
      const isOverdue = p.status !== "Paid" && p.due_date && new Date(p.due_date) < today;
      const sc = p.status === "Paid" ? { bg: "#f0fdf4", br: "#bbf7d0", c: "#16a34a" } : isOverdue ? { bg: "#fff1f2", br: "#fecdd3", c: "#e11d48" } : { bg: "#fff7ed", br: "#fed7aa", c: "#ea580c" };
      return (
        <span style={{ background: sc.bg, border: `1px solid ${sc.br}`, color: sc.c, borderRadius: 4, padding: "3px 8px", fontSize: 9, fontWeight: 700 }}>{p.status}</span>
      );
    }},
    { header: 'Paid Date', render: (p) => (
      <div style={{ color: '#64748b', fontSize: 11 }}>{p.paid_date ? new Date(p.paid_date).toLocaleDateString("en-IN") : "—"}</div>
    )},
    { header: 'Actions', align: 'center', render: (p) => (
      canEdit && (
        <div style={{ display: "flex", gap: 6, justifyContent: 'center' }}>
          <Button variant="ghost" onClick={() => openForm(p)} style={{ fontSize: 9, padding: "3px 8px" }}>Edit</Button>
          {isAdmin && <Button variant="danger" onClick={() => { if (window.confirm("Delete this payable?")) onDelete(p.id); }} style={{ fontSize: 9, padding: "3px 8px", minWidth: "auto", minHeight: "auto" }}>Del</Button>}
        </div>
      )
    )},
  ];

  const receivableDetailColumns: Column<Bill>[] = [
    { header: 'INV NO', render: (b) => <div style={{ fontWeight: 600, color: '#0f172a' }}>{b.inv_no}</div> },
    { header: 'SITE', render: (b) => <div style={{ fontSize: 11, color: '#ea580c' }}>{b.site}</div> },
    { header: 'BILL DETAILS', render: (b) => <div style={{ fontSize: 11, color: '#64748b' }}>{b.bill_details || "-"}</div> },
    { header: 'TOTAL+GST', align: 'right', render: (b) => <div style={{ fontFamily: "IBM Plex Mono,monospace" }}>₹{parseFloat(b.amount_with_gst as any || "0").toLocaleString("en-IN")}</div> },
    { header: 'BALANCE', align: 'right', render: (b) => <div style={{ fontWeight: 700, color: "#dc2626", fontFamily: "IBM Plex Mono,monospace" }}>₹{getBal(b).toLocaleString("en-IN")}</div> },
    { header: 'STATUS', render: (b) => (
      <span style={{ fontSize: 9, fontWeight: 700, padding: "2px 6px", borderRadius: 4, background: "#fff7ed", border: "1px solid #fed7aa", color: "#ea580c" }}>{b.bill_status}</span>
    )},
  ];

  const payableDetailColumns: Column<Payable>[] = [
    { header: 'VENDOR', render: (p) => (
      <div style={{ fontWeight: 600, color: "#0f172a" }}>
        {p.vendor}
        {p.vendor_gstin && <div style={{ fontSize: 9, color: "#94a3b8", fontWeight: 400 }}>{p.vendor_gstin}</div>}
      </div>
    )},
    { header: 'SITE', render: (p) => <div style={{ fontSize: 11, color: "#ea580c" }}>{p.site}</div> },
    { header: 'DESCRIPTION', render: (p) => <div style={{ fontSize: 11, color: "#64748b", maxWidth: 160 }}>{p.description || "-"}</div> },
    { header: 'BASE AMT', align: 'right', render: (p) => <div style={{ fontWeight: 700, color: "#dc2626", fontFamily: "IBM Plex Mono,monospace" }}>₹{parseFloat(p.amount as string || "0").toLocaleString("en-IN", { maximumFractionDigits: 0 })}</div> },
    { header: 'TOTAL+GST', align: 'right', render: (p) => <div style={{ fontFamily: "IBM Plex Mono,monospace", color: "#0f172a" }}>{p.amount_with_gst ? `₹${parseFloat(p.amount_with_gst as string).toLocaleString("en-IN", { maximumFractionDigits: 0 })}` : "-"}</div> },
    { header: 'DUE DATE', render: (p) => {
      const isOD = p.status !== "Paid" && p.due_date && new Date(p.due_date) < today;
      return (
        <div style={{ color: isOD ? "#dc2626" : "#64748b", fontWeight: isOD ? 700 : 400, whiteSpace: "nowrap" }}>
          {p.due_date ? new Date(p.due_date).toLocaleDateString("en-IN") : "-"}
          {isOD && <span style={{ fontSize: 9, marginLeft: 4 }}>OVERDUE</span>}
        </div>
      );
    }},
    { header: 'STATUS', render: (p) => {
      const isOD = p.status !== "Paid" && p.due_date && new Date(p.due_date) < today;
      const sc = p.status === "Paid" ? { bg: "#f0fdf4", br: "#bbf7d0", c: "#16a34a" } : isOD ? { bg: "#fff1f2", br: "#fecdd3", c: "#e11d48" } : { bg: "#fff7ed", br: "#fed7aa", c: "#ea580c" };
      return <span style={{ fontSize: 9, fontWeight: 700, padding: "2px 6px", borderRadius: 4, background: sc.bg, border: `1px solid ${sc.br}`, color: sc.c }}>{p.status}</span>;
    }},
    { header: 'PAID DATE', render: (p) => <div style={{ fontSize: 11, color: "#64748b" }}>{p.paid_date ? new Date(p.paid_date).toLocaleDateString("en-IN") : "-"}</div> },
  ];




  if (pLoading && payables.length === 0) return <div style={{ padding: 40, textAlign: 'center' }}>Loading payables...</div>;

  return (
    <div>
      {/* Outstanding by Site */}
      {siteOutstanding.length > 0 && (
        <div style={{ marginBottom: 14 }}>
          <div style={{ fontSize: 10, color: "#94a3b8", fontWeight: 700, letterSpacing: 1, marginBottom: 8 }}>OUTSTANDING BY SITE</div>
          <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
            {siteOutstanding.map(s => (
              <div key={s.site} onClick={() => { setCdSite(s.site); setCardDetail("site:" + s.site); }} style={{ background: "#fff", border: "1px solid #fecdd3", borderRadius: 8, padding: "10px 14px", cursor: "pointer", minWidth: 110, textAlign: "center", transition: "all .15s" }}>
                <div style={{ fontSize: 9, color: "#94a3b8", fontWeight: 700, letterSpacing: 1, marginBottom: 4, textTransform: "uppercase" }}>{s.site}</div>
                <div style={{ fontSize: 15, fontWeight: 800, color: "#dc2626", fontFamily: "IBM Plex Mono,monospace" }}>₹{Math.round(s.amt).toLocaleString("en-IN")}</div>
                <div style={{ fontSize: 9, color: "#94a3b8", marginTop: 2 }}>{s.count} {s.count > 1 ? "invoices" : "invoice"}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Main Tiles */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))", gap: 12, marginBottom: 18 }}>
        {[
          { key: "outstanding", l: "OUTSTANDING PAYABLE", v: fmt(totalPending), c: "#dc2626", sub: `${payables.filter(p => p.status !== "Paid").length} pending` },
          { key: "overdue", l: "OVERDUE PAYABLES", v: overdue + " bills", c: "#ea580c", sub: "past due date" },
          { key: "receivable", l: "TOTAL RECEIVABLE", v: fmt(totalReceivable), c: "#f97316", sub: "from clients" },
          { key: "bank", l: "BANK BALANCE", v: (banks.length > 0 || bankBalanceRaw) ? fmt(bb) : "Not set", c: "#2563eb", sub: bbUpdated ? `Updated: ${new Date(bbUpdated).toLocaleString("en-IN")}` : "Not updated", clickEdit: isAdmin },
          { key: "od", l: "OD UTILISED", v: odUsed > 0 ? fmt(odUsed) : "Nil", c: odUsed > 0 ? "#7c3aed" : "#16a34a", sub: odUsed > 0 ? "overdraft in use" : "no OD used" },
          { key: "net", l: "NET CASH POSITION", v: fmt(netPos), c: netPos >= 0 ? "#16a34a" : "#dc2626", sub: netPos >= 0 ? "surplus" : "deficit" },
          { key: "paid", l: "PAID THIS CYCLE", v: fmt(totalPaidDisplay), c: "#64748b", sub: `${payables.filter(p => p.status === "Paid").length} paid` },
        ].map(card => (
          <div 
            key={card.l} 
            onClick={() => {
              if (card.clickEdit && card.key === 'bank') {
                const val = prompt("Enter main bank balance:", bankBalance);
                if (val !== null) handleSaveBankBalance(val);
              } else {
                if (card.key === 'paid') {
                   const now = new Date();
                   setCdFrom(new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0, 10));
                   setCdTo(new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString().slice(0, 10));
                }
                setCardDetail(card.key);
              }
            }}
            style={{ background: "#fff", border: "1px solid #e2e8f0", borderRadius: 10, padding: "14px 16px", cursor: "pointer" }}
          >
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 }}>
              <div style={{ fontSize: 8, color: "#94a3b8", letterSpacing: 2 }}>{card.l}</div>
              <span style={{ fontSize: 8, color: card.c, background: card.c + "15", border: "1px solid " + card.c + "30", padding: "1px 5px", borderRadius: 3 }}>
                {card.clickEdit ? "EDIT" : "VIEW"}
              </span>
            </div>
            <div style={{ fontSize: card.v.length > 10 ? 16 : 22, fontWeight: 700, color: card.c, fontFamily: "IBM Plex Mono,monospace" }}>{card.v}</div>
            <div style={{ fontSize: 10, color: "#94a3b8", marginTop: 3 }}>{card.sub}</div>
          </div>
        ))}
      </div>

      {/* Bank Accounts Section */}
      {isAdmin && (
        <div style={{ marginBottom: 14 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
            <div style={{ fontSize: 10, color: "#2563eb", letterSpacing: 2, fontWeight: 700 }}>BANK ACCOUNTS</div>
            <Button variant="ghost" onClick={() => {
              const name = prompt("Enter bank name:");
              if (!name) return;
              const accNo = prompt("Enter account no:");
              const bal = prompt("Enter balance:");
              const isOD = window.confirm("Is this an OD account?");
              let odLimit = undefined;
              if (isOD) {
                const lim = prompt("Enter OD Limit:");
                if (lim) odLimit = parseFloat(lim);
              }
              const newBanks = [...banks, { name, account_no: accNo || "", balance: parseFloat(bal || "0"), isOD, odLimit } as BankAccount];
              handleSaveBanks(newBanks);
            }}>+ Add Bank</Button>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))", gap: 8, marginBottom: 14 }}>
            {banks.map((bank, bi) => {
              const bal = parseFloat(bank.balance as any || 0);
              const isOD = bank.isOD;
              const color = bal === 0 ? "#94a3b8" : (isOD && bal > 0 ? "#dc2626" : "#16a34a");
              const limit = parseFloat(bank.odLimit as any || 0);
              const used = bal;
              const avail = Math.max(0, limit - used);
              const pct = limit > 0 ? Math.min(100, Math.round((used / limit) * 100)) : 0;
              const barColor = pct >= 80 ? "#dc2626" : pct >= 50 ? "#ea580c" : "#16a34a";

              return (
                <div key={bi} style={{ background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: 8, padding: "10px 14px" }}>
                  <div style={{ display: "flex", justifyContent: "space-between" }}>
                    <div>
                      <div style={{ fontWeight: 700, fontSize: 12, color: "#0f172a" }}>{bank.name}</div>
                      <div style={{ fontSize: 10, color: "#64748b" }}>{bank.account_no}</div>
                    </div>
                    {isOD && <span style={{ background: "#fef3c7", border: "1px solid #fde68a", color: "#d97706", fontSize: 9, padding: "1px 5px", borderRadius: 3, fontWeight: 700 }}>OD</span>}
                  </div>
                  <div 
                    style={{ fontSize: 18, fontWeight: 700, color, fontFamily: "IBM Plex Mono,monospace", marginTop: 6, cursor: "pointer" }}
                    onClick={() => {
                      const b = prompt(`Update balance for ${bank.name}:`, bal.toString());
                      if (b !== null) {
                        const newBanks = [...banks];
                        newBanks[bi] = { ...newBanks[bi], balance: parseFloat(b) } as any;
                        handleSaveBanks(newBanks);
                      }
                    }}
                  >
                    {isOD && bal > 0 ? "-" : ""}₹{Math.abs(bal).toLocaleString("en-IN")}
                  </div>

                  {isOD && limit > 0 && (
                    <div style={{ marginTop: 8 }}>
                      <div style={{ display: "flex", justifyContent: "space-between", fontSize: 10, color: "#64748b", marginBottom: 3 }}>
                        <span>Limit: <b style={{ color: "#7c3aed" }}>₹{limit.toLocaleString("en-IN")}</b></span>
                        <span style={{ color: barColor, fontWeight: 700 }}>{pct}% used</span>
                      </div>
                      <div style={{ background: "#e9d5ff", borderRadius: 4, height: 6, overflow: "hidden" }}>
                        <div style={{ width: `${pct}%`, background: barColor, height: "100%", borderRadius: 4, transition: "width 0.4s" }} />
                      </div>
                      <div style={{ display: "flex", justifyContent: "space-between", fontSize: 10, marginTop: 3 }}>
                        <span style={{ color: "#dc2626" }}>Used: <b>₹{used.toLocaleString("en-IN")}</b></span>
                        <span style={{ color: "#16a34a" }}>Avail: <b>₹{avail.toLocaleString("en-IN")}</b></span>
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}

      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 }}>
        <div style={{ fontWeight: 700, fontSize: 14, color: "#0f172a" }}>Payables Register</div>
        <div style={{ display: "flex", gap: 8 }}>
          <Button variant="ghost" onClick={handlePrintRegister} style={{ fontSize: 10 }}>⬇ PDF</Button>
          {canEdit && (
            <span>
              <input id="payFileInput" type="file" accept=".xlsx,.xls" style={{ display: "none" }} onChange={(e) => { if (e.target.files?.[0]) handlePayImport(e.target.files[0]); e.target.value = ""; }} />
              <Button variant="ghost" onClick={() => document.getElementById("payFileInput")?.click()} style={{ fontSize: 10 }}>Import Bills</Button>
            </span>
          )}
          {canEdit && (
            <span>
              <input id="monthlyExpFileInput" type="file" accept=".xlsx,.xls" style={{ display: "none" }} onChange={(e) => { if (e.target.files?.[0]) handleMonthlyExpenseImport(e.target.files[0]); e.target.value = ""; }} />
              <Button variant="ghost" onClick={() => document.getElementById("monthlyExpFileInput")?.click()} style={{ fontSize: 10, background: "#f8fafc" }}>📥 Import Expenses</Button>
            </span>
          )}
          <Button variant="ghost" onClick={handlePayExportTemplate} style={{ fontSize: 10 }}>⬇ Template</Button>
          {canEdit && <Button variant="info" onClick={() => { setBpForm({ vendor: "", amount: "", paid_date: new Date().toISOString().slice(0, 10), payment_mode: "NEFT", remarks: "" }); setBpResult(null); setShowBulkPay(true); }} style={{ fontSize: 10, background: "#0891b2", borderColor: "#0891b2" }}>💸 Bulk Payment</Button>}
          {canEdit && <Button onClick={() => openForm(null)} style={{ fontSize: 10 }}>+ Add Payable</Button>}
        </div>
      </div>

      <div style={{ marginBottom: 10, display: "flex", gap: 8, alignItems: "center" }}>
        <input type="text" placeholder="🔍 Search vendor, invoice, site..." value={vendorSearch} onChange={e => setVendorSearch(e.target.value)} style={{ flex: 1, padding: "8px 12px", border: "1px solid #e2e8f0", borderRadius: 8, fontSize: 12, outline: "none", background: "#f8fafc" }} />
        {vendorSearch.trim() && <span style={{ fontSize: 11, color: "#64748b" }}>{filteredPayables.length} results</span>}
      </div>

      <DataTable 
        columns={columns} 
        data={filteredPayables} 
        loading={pLoading} 
        rowStyle={(p) => {
          const isOverdue = p.status !== "Paid" && p.due_date && new Date(p.due_date) < today;
          return { background: isOverdue ? "#fff8f8" : "#fff" };
        }}
      />

      {modal === "form" && (
        <Modal title={form.id ? "Edit Payable" : "Add Payable"} onClose={() => setModal(null)} wide>
          <PayableFormModal form={form} setForm={setForm} saving={saving} onSave={handleSave} onClose={() => setModal(null)} sites={SITES} />
        </Modal>
      )}

      {vendorLedger && (
        <Modal title={`Vendor Ledger - ${vendorLedger.vendor}`} onClose={() => setVendorLedger(null)} wide>
          <VendorLedgerModal vendorLedger={vendorLedger} onClose={() => setVendorLedger(null)} />
        </Modal>
      )}

      {showBulkPay && (
        <Modal title="💸 Bulk Payment — Split Across Invoices" onClose={() => { setShowBulkPay(false); setBpResult(null); }} wide>
          <BulkPayModal payables={payables} form={bpForm} setForm={setBpForm} result={bpResult} setResult={setBpResult} saving={saving} onClose={() => { setShowBulkPay(false); setBpResult(null); }} onConfirm={onBulkPay} />
        </Modal>
      )}

      {cardDetail && (
        <Modal 
          title={cardDetail && cardDetail.startsWith("site:") ? `Outstanding: ${cardDetail.slice(5)}` : ({ outstanding: "Outstanding Payables", overdue: "Overdue Payables", receivable: "Bills Receivable", net: "All Payables", paid: "Paid This Cycle", od: "OD Utilization" } as any)[cardDetail] || cardDetail} 
          onClose={() => { setCardDetail(null); setCdFrom(""); setCdTo(""); setCdSite(""); }} wide
          headerActions={
            <Button variant="ghost" onClick={() => printCardPDF(cardDetail!)} style={{ fontSize: 10 }}>⬇ PDF</Button>
          }
        >
           {cardDetail === 'od' ? (
             <div style={{ padding: 10 }}>
               <table style={{ width: "100%", borderCollapse: "collapse" }}>
                 <thead>
                   <tr style={{ background: "#f1f5f9" }}>
                     {["BANK NAME", "ACCOUNT NO", "OD LIMIT", "UTILIZED BALANCE"].map(h => (
                       <th key={h} style={{ padding: "8px 12px", textAlign: "left", fontSize: 10, color: "#64748b", fontFamily: "IBM Plex Mono,monospace" }}>{h}</th>
                     ))}
                   </tr>
                 </thead>
                 <tbody>
                   {banks.filter(b => b.isOD).map((b, i) => (
                     <tr key={i} style={{ borderBottom: "1px solid #e2e8f0" }}>
                       <td style={{ padding: "10px 12px", fontWeight: 700 }}>{b.name}</td>
                       <td style={{ padding: "10px 12px", color: "#64748b" }}>{b.account_no}</td>
                       <td style={{ padding: "10px 12px", fontFamily: "IBM Plex Mono,monospace" }}>₹{(b.odLimit || 0).toLocaleString("en-IN")}</td>
                       <td style={{ padding: "10px 12px", fontWeight: 700, color: "#dc2626", fontFamily: "IBM Plex Mono,monospace" }}>₹{parseFloat(b.balance as any || 0).toLocaleString("en-IN")}</td>
                     </tr>
                   ))}
                   {banks.filter(b => b.isOD).length === 0 && <tr><td colSpan={4} style={{ padding: 20, textAlign: 'center', color: '#94a3b8' }}>No OD accounts utilized.</td></tr>}
                 </tbody>
               </table>
             </div>
           ) : (
             <>
               <div style={{ padding: "8px 16px", borderBottom: "1px solid #f1f5f9", display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap", background: "#f8fafc" }}>
                  <span style={{ fontSize: 10, color: "#94a3b8", fontWeight: 700 }}>FILTER:</span>
                  <div style={{ display: "flex", gap: 4, alignItems: "center" }}>
                    <span style={{ fontSize: 10, color: "#64748b" }}>From</span>
                    <input type="date" value={cdFrom} onChange={e => setCdFrom(e.target.value)} style={{ padding: "3px 7px", border: "1px solid #e2e8f0", borderRadius: 5, fontSize: 11, outline: "none" }} />
                  </div>
                  <div style={{ display: "flex", gap: 4, alignItems: "center" }}>
                    <span style={{ fontSize: 10, color: "#64748b" }}>To</span>
                    <input type="date" value={cdTo} onChange={e => setCdTo(e.target.value)} style={{ padding: "3px 7px", border: "1px solid #e2e8f0", borderRadius: 5, fontSize: 11, outline: "none" }} />
                  </div>
                  <select value={cdSite} onChange={e => setCdSite(e.target.value)} style={{ padding: "3px 7px", border: "1px solid #e2e8f0", borderRadius: 5, fontSize: 11, outline: "none" }}>
                    <option value="">All Sites</option>
                    {Array.from(new Set(payables.map(p => p.site))).sort().map(s => <option key={s} value={s}>{s}</option>)}
                  </select>
                  <Button variant="ghost" onClick={() => { setCdFrom(""); setCdTo(""); setCdSite(""); }} style={{ fontSize: 10, padding: "3px 8px" }}>Clear</Button>
               </div>
               <DataTable 
                 columns={cardDetail === 'receivable' ? (receivableDetailColumns as any) : (payableDetailColumns as any)} 
                 data={cardDetailItems(cardDetail)}
                 rowStyle={(p: any) => {
                   if (cardDetail === 'receivable') return {};
                   const isOD = p.status !== "Paid" && p.due_date && new Date(p.due_date) < today;
                   return isOD ? { background: "#fff8f8" } : {};
                 }}
               />
             </>
           )}
        </Modal>
      )}

    </div>
  );
};
